import { useState } from 'react';
import { Copy, Download, FileText, CheckCircle } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { useSaveExportToFile } from '@/hooks/useCommunity';
import { useToast } from '@/providers/toast-provider';
import type { ExportBundle } from '@/hooks/useCommunity';

interface ExportReviewDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  bundle: ExportBundle;
  includedFeedback: boolean;
}

export function ExportReviewDialog({
  open,
  onOpenChange,
  bundle,
  includedFeedback: _includedFeedback,
}: ExportReviewDialogProps) {
  const { notify } = useToast();
  const saveExport = useSaveExportToFile();
  const [copied, setCopied] = useState(false);

  // Generate Markdown content
  const generateMarkdown = (): string => {
    let md = `# CogniCal Community Feedback Export\n\n`;
    md += `> Generated at: ${bundle.systemInfo.timestamp}\n\n`;

    // System Information
    md += `## System Information\n\n`;
    md += `- **OS**: ${bundle.systemInfo.os}\n`;
    md += `- **App Version**: ${bundle.systemInfo.appVersion}\n`;
    md += `- **Locale**: ${bundle.systemInfo.locale}\n\n`;

    // Anonymized Metrics
    md += `## Anonymized Usage Metrics\n\n`;
    md += `- **Total Tasks**: ${bundle.metrics.totalTasks}\n`;
    md += `- **Completed Tasks**: ${bundle.metrics.completedTasks}\n`;
    if (bundle.metrics.averageCompletionTimeMinutes) {
      md += `- **Avg Completion Time**: ${bundle.metrics.averageCompletionTimeMinutes.toFixed(1)} minutes\n`;
    }
    md += `- **Total Sessions**: ${bundle.metrics.totalSessions}\n`;
    md += `- **Productivity Score**: ${bundle.metrics.productivityScoreAvailable ? 'Available' : 'Not Available'}\n`;
    md += `- **Workload Forecasts**: ${bundle.metrics.workloadForecastsCount}\n`;
    md += `- **Wellness Events**: ${bundle.metrics.wellnessEventsCount}\n\n`;

    // Feedback Summary
    if (bundle.feedbackSummary) {
      const fs = bundle.feedbackSummary;
      md += `## AI Feedback Summary\n\n`;
      md += `- **Total Feedback**: ${fs.totalFeedbackCount}\n`;
      md += `- **Positive (👍)**: ${fs.positiveCount}\n`;
      md += `- **Negative (👎)**: ${fs.negativeCount}\n`;
      if (fs.surfaces.length > 0) {
        md += `- **Surfaces**: ${fs.surfaces.join(', ')}\n`;
      }
      if (fs.mostCommonIssues.length > 0) {
        md += `- **Common Issues**:\n`;
        fs.mostCommonIssues.forEach((issue) => {
          md += `  - ${issue}\n`;
        });
      }
      md += `\n`;
    }

    // Plugins
    if (bundle.plugins.length > 0) {
      md += `## Detected Plugins\n\n`;
      bundle.plugins.forEach((plugin) => {
        md += `### ${plugin.name}\n`;
        if (plugin.version) {
          md += `- **Version**: ${plugin.version}\n`;
        }
        md += `- **Source**: ${plugin.source}\n`;
        md += `- **Enabled**: ${plugin.enabled}\n`;
        if (plugin.permissions.length > 0) {
          md += `- **Permissions**: ${plugin.permissions.join(', ')}\n`;
        }
        md += `\n`;
      });
    } else {
      md += `## Detected Plugins\n\n_No plugins detected_\n\n`;
    }

    // Checksum
    md += `## Verification\n\n`;
    md += `**Checksum (SHA-256)**: \`${bundle.checksum}\`\n\n`;
    md += `---\n\n`;
    md += `_This export was generated by CogniCal and contains only anonymized data. No personal information, task names, or notes are included._\n`;

    return md;
  };

  const markdownContent = generateMarkdown();

  const handleCopyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(markdownContent);
      setCopied(true);
      notify({
        title: '已复制',
        description: '导出内容已复制到剪贴板',
        variant: 'success',
      });
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      notify({
        title: '复制失败',
        description: error instanceof Error ? error.message : '无法复制到剪贴板',
        variant: 'error',
      });
    }
  };

  const handleSaveToFile = async () => {
    try {
      // In a real implementation, this would open a file save dialog
      // For now, we'll save to a default location
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const filename = `cognical-export-${timestamp}.md`;

      // Note: In Tauri, we'd use the dialog API to let user choose location
      // For now, save to a temp location
      await saveExport.mutateAsync({
        bundle,
        filePath: filename,
      });

      notify({
        title: '导出成功',
        description: `已保存到 ${filename}`,
        variant: 'success',
      });
      onOpenChange(false);
    } catch (error) {
      notify({
        title: '保存失败',
        description: error instanceof Error ? error.message : '无法保存文件',
        variant: 'error',
      });
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[80vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            预览导出内容
          </DialogTitle>
          <DialogDescription>请在分享前检查导出内容,确认不包含敏感信息</DialogDescription>
        </DialogHeader>

        <div className="flex-1 overflow-hidden space-y-4">
          {/* Summary Stats */}
          <div className="flex flex-wrap gap-2">
            <Badge variant="outline">
              任务: {bundle.metrics.totalTasks} ({bundle.metrics.completedTasks} 完成)
            </Badge>
            <Badge variant="outline">会话: {bundle.metrics.totalSessions}</Badge>
            {bundle.feedbackSummary && (
              <Badge variant="outline">
                反馈: {bundle.feedbackSummary.totalFeedbackCount} ( 👍{' '}
                {bundle.feedbackSummary.positiveCount} / 👎 {bundle.feedbackSummary.negativeCount})
              </Badge>
            )}
            {!bundle.feedbackSummary && <Badge variant="outline">不包含反馈</Badge>}
          </div>

          {/* Preview Content */}
          <div className="flex-1 overflow-auto border rounded-md">
            <Textarea
              value={markdownContent}
              readOnly
              className="min-h-[400px] font-mono text-xs resize-none border-0"
            />
          </div>

          {/* Checksum */}
          <div className="text-xs text-muted-foreground">
            <span className="font-medium">校验和 (SHA-256):</span>{' '}
            <code className="bg-muted px-1 py-0.5 rounded">{bundle.checksum}</code>
          </div>
        </div>

        <DialogFooter className="flex-row gap-2">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            取消
          </Button>
          <Button variant="outline" onClick={handleCopyToClipboard} className="gap-2">
            {copied ? (
              <>
                <CheckCircle className="h-4 w-4" />
                已复制
              </>
            ) : (
              <>
                <Copy className="h-4 w-4" />
                复制到剪贴板
              </>
            )}
          </Button>
          <Button onClick={handleSaveToFile} disabled={saveExport.isPending} className="gap-2">
            <Download className="h-4 w-4" />
            {saveExport.isPending ? '保存中...' : '保存为文件'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
